export const euCountries = [
    { name: 'Austria', code: 'AT', dial_code: '+43', flag: 'AT', currency: 'EUR', currency_sign: '€' },
    { name: 'Belgium', code: 'BE', dial_code: '+32', flag: 'BE', currency: 'EUR', currency_sign: '€' },
    { name: 'Bulgaria', code: 'BG', dial_code: '+359', flag: 'BG', currency: 'BGN', currency_sign: 'лв' },
    { name: 'Croatia', code: 'HR', dial_code: '+385', flag: 'HR', currency: 'EUR', currency_sign: '€' },
    { name: 'Cyprus', code: 'CY', dial_code: '+357', flag: 'CY', currency: 'EUR', currency_sign: '€' },
    {
        name: 'Czech Republic',
        code: 'CZ',
        dial_code: '+420',
        flag: 'CZ',
        currency: 'CZK',
        currency_sign: 'Kč',
    },
    { name: 'Denmark', code: 'DK', dial_code: '+45', flag: 'DK', currency: 'DKK', currency_sign: 'kr' },
    { name: 'Estonia', code: 'EE', dial_code: '+372', flag: 'EE', currency: 'EUR', currency_sign: '€' },
    { name: 'Finland', code: 'FI', dial_code: '+358', flag: 'FI', currency: 'EUR', currency_sign: '€' },
    { name: 'France', code: 'FR', dial_code: '+33', flag: 'FR', currency: 'EUR', currency_sign: '€' },
    { name: 'Germany', code: 'DE', dial_code: '+49', flag: 'DE', currency: 'EUR', currency_sign: '€' },
    { name: 'Greece', code: 'GR', dial_code: '+30', flag: 'GR', currency: 'EUR', currency_sign: '€' },
    { name: 'Ireland', code: 'IE', dial_code: '+353', flag: 'IE', currency: 'EUR', currency_sign: '€' },
    { name: 'Italy', code: 'IT', dial_code: '+39', flag: 'IT', currency: 'EUR', currency_sign: '€' },
    { name: 'Latvia', code: 'LV', dial_code: '+371', flag: 'LV', currency: 'EUR', currency_sign: '€' },
    { name: 'Lithuania', code: 'LT', dial_code: '+370', flag: 'LT', currency: 'EUR', currency_sign: '€' },
    { name: 'Luxembourg', code: 'LU', dial_code: '+352', flag: 'LU', currency: 'EUR', currency_sign: '€' },
    { name: 'Malta', code: 'MT', dial_code: '+356', flag: 'MT', currency: 'EUR', currency_sign: '€' },
    { name: 'Netherlands', code: 'NL', dial_code: '+31', flag: 'NL', currency: 'EUR', currency_sign: '€' },
    { name: 'Poland', code: 'PL', dial_code: '+48', flag: 'PL', currency: 'PLN', currency_sign: 'zł' },
    { name: 'Portugal', code: 'PT', dial_code: '+351', flag: 'PT', currency: 'EUR', currency_sign: '€' },
    { name: 'Romania', code: 'RO', dial_code: '+40', flag: 'RO', currency: 'RON', currency_sign: 'lei' },
    { name: 'Slovakia', code: 'SK', dial_code: '+421', flag: 'SK', currency: 'EUR', currency_sign: '€' },
    { name: 'Slovenia', code: 'SI', dial_code: '+386', flag: 'SI', currency: 'EUR', currency_sign: '€' },
    { name: 'Spain', code: 'ES', dial_code: '+34', flag: 'ES', currency: 'EUR', currency_sign: '€' },
    { name: 'Sweden', code: 'SE', dial_code: '+46', flag: 'SE', currency: 'SEK', currency_sign: 'kr' },
]
